name: Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  ruby:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Run script
      env:
        TOGGL_API_TOKEN: ${{ secrets.TOGGL_API_TOKEN }}
        TOGGL_WORKSPACE_ID: ${{ secrets.TOGGL_WORKSPACE_ID }}
        HABITRA_ID: ${{ secrets.HABITRA_ID }}
        HABITRA_PASSWORD: ${{ secrets.HABITRA_PASSWORD }}
      run: TZ=Asia/Tokyo ruby app.rb
